# CF Server Monitor Go Probe configuration
#
# 第一次启动时会复制到：
# /data/adb/cf-server-monitor/config.conf
#
# 后续可以通过 KernelSU WebUI 修改。

SERVER_ID=""
SECRET=""
WORKER_URL=""

COLLECT_INTERVAL="0"
REPORT_INTERVAL="60"

CT_NODE=""
CU_NODE=""
CM_NODE=""
BD_NODE=""

INTERFACE=""

RESET_DAY="1"

CONNECTION_MODE="http"

AUTO_UPDATE="0"
UPDATE_PROXY=""

CONFIG_MD5="none"