# CF Server Monitor Android / KernelSU 配置

ID=""
SECRET=""
URL=""

INTERVAL="60"
COLLECT_INTERVAL="0"

CONNECTION_MODE="http"

# 是否输出详细调试日志
# 0=关闭
# 1=开启
DEBUG="0"

# 单个日志文件最大大小，单位 MB
LOG_MAX_SIZE_MB="5"

# 保留历史日志数量
LOG_KEEP_COUNT="3"