# CF Server Monitor Android / KernelSU 配置

SERVER_ID=""
SECRET=""
WORKER_URL=""

COLLECT_INTERVAL="0"
REPORT_INTERVAL="60"

CT_NODE=""
CU_NODE=""
CM_NODE=""
BD_NODE=""

INTERFACE=""

RESET_DAY="1"

CONNECTION_MODE="auto"

AUTO_UPDATE="0"
UPDATE_PROXY=""

CONFIG_MD5="none"

# 是否输出详细调试日志
# 0=关闭
# 1=开启
DEBUG="0"

# 单个日志文件最大大小，单位 MB
LOG_MAX_SIZE_MB="5"

# 保留历史日志数量
LOG_KEEP_COUNT="3"